import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const fullPath = path.join(root, "公众号完整稿.md");
const publishPath = path.join(root, "公众号发布稿.md");
const browserMdPath = path.join(root, "公众号发布稿_浏览器版.md");
const htmlPath = path.join(root, "公众号发布稿_浏览器版.wechat.html");

let md = await fs.readFile(fullPath, "utf8");

// The WeChat editor has a separate title field. Keeping the H1 in the pasted
// body creates a duplicated title, so remove only the first top-level heading.
md = md.replace(/^# .+\n+/, "");

// md2wechat turns image alt text into visible figcaptions. In this workflow the
// surrounding paragraphs already introduce each visual, so alt text would leak
// into the article body as noise after pasting into the WeChat editor.
md = md.replace(/!\[[^\]]*\]\(([^)]+)\)/g, "![]($1)");

// The default md2wechat theme auto-numbers H2 headings. Remove handwritten
// numeric prefixes to avoid headings like "1. 1. 问题变了".
md = md.replace(/^##\s+\d+[.、]\s+/gm, "## ");

await fs.writeFile(publishPath, md, "utf8");
await fs.writeFile(browserMdPath, md, "utf8");

try {
  let html = await fs.readFile(htmlPath, "utf8");
  html = html.replace(/<figcaption\b[^>]*>[\s\S]*?<\/figcaption>/g, "");
  html = html.replace(/<h1\b[\s\S]*?<\/h1>\s*/i, "");
  await fs.writeFile(htmlPath, html, "utf8");
} catch {
  // The HTML is generated by md2wechat in the next step when it does not exist yet.
}
